# Generated by Django 5.2.1 on 2025-06-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('idOrBirthCertificate', models.CharField(max_length=30)),
                ('contactPhone', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
                ('remarks', models.TextField()),
            ],
        ),
    ]
