# Generated by Django 5.2.1 on 2025-06-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeMaterials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Electronics',
        ),
    ]
