# Generated by Django 5.2.1 on 2025-06-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeMaterials', '0002_rename_student_electronics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronics',
            old_name='address',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='contactPhone',
            new_name='ProductName',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='firstName',
            new_name='Product_Type',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='idOrBirthCertificate',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='town',
        ),
    ]
