# Generated by Django 5.2.1 on 2025-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeMaterials', '0003_rename_address_electronics_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
