# Generated by Django 5.2.1 on 2025-07-12 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 14, 47, 4, 22795, tzinfo=datetime.timezone.utc)),
        ),
    ]
