# Generated by Django 5.2.1 on 2025-07-12 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 19, 42, 15, 458086, tzinfo=datetime.timezone.utc)),
        ),
    ]
