# Generated by Django 5.2.1 on 2025-07-18 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_department_alter_attendancerecord_date_timetable'),
        ('users', '0007_department_alter_customuser_department_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 21, 53, 24, 59976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
