# Generated by Django 5.2.1 on 2025-07-18 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_timetable_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 21, 53, 57, 517120, tzinfo=datetime.timezone.utc)),
        ),
    ]
