# Generated by Django 5.2.1 on 2025-07-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Administrator', 'Admin'), ('Teacher', 'Teacher'), ('Secretary', 'Secretary')], max_length=100, null=True),
        ),
    ]
