# Generated by Django 5.2.1 on 2025-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('secretary', 'Secretary')], max_length=100, null=True),
        ),
    ]
